"""Phase 2 Initial Migration

Revision ID: c5ecd15bcd12
Revises: 
Create Date: 2026-09-28 14:41:30.133156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ecd15bcd12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('TRAINEE', 'TRAINING_PROVIDER', 'EMPLOYER', 'GOVERNMENT_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('apaar_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('masked_apaar_id', sa.String(), nullable=False),
    sa.Column('apaar_hash', sa.String(), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apaar_identities_apaar_hash'), 'apaar_identities', ['apaar_hash'], unique=True)
    op.create_index(op.f('ix_apaar_identities_user_id'), 'apaar_identities', ['user_id'], unique=True)
    op.create_table('employers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_user_id'), 'employers', ['user_id'], unique=True)
    op.create_table('government_admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_admins_user_id'), 'government_admins', ['user_id'], unique=True)
    op.create_table('learner_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('current_employment_status', sa.Enum('EMPLOYED', 'SELF_EMPLOYED', 'FREELANCER', 'ENTREPRENEUR', 'APPRENTICESHIP', 'HIGHER_STUDIES', 'SEEKING_EMPLOYMENT', 'NOT_CURRENTLY_WORKING', name='employmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=True)
    op.create_table('training_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_providers_user_id'), 'training_providers', ['user_id'], unique=True)
    op.create_table('career_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('ENROLLMENT', 'TRAINING_COMPLETED', 'CERTIFICATION', 'EMPLOYMENT_STARTED', 'EMPLOYMENT_CHANGED', 'PROMOTION', 'SALARY_CHANGE', 'SELF_EMPLOYMENT_STARTED', 'HIGHER_STUDIES', 'OTHER', name='careereventtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_events_learner_id'), 'career_events', ['learner_id'], unique=False)
    op.create_table('learner_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('proficiency_score', sa.Integer(), nullable=False),
    sa.Column('proficiency_source', sa.Enum('TRAINING', 'ASSESSMENT', 'EMPLOYER', 'LEARNER', 'AI', name='proficiencysource'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'skill_id', name='uq_learner_skill')
    )
    op.create_index(op.f('ix_learner_skills_learner_id'), 'learner_skills', ['learner_id'], unique=False)
    op.create_index(op.f('ix_learner_skills_skill_id'), 'learner_skills', ['skill_id'], unique=False)
    op.create_table('training_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programs_provider_id'), 'training_programs', ['provider_id'], unique=False)
    op.create_table('training_enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('learner_id', sa.Uuid(), nullable=False),
    sa.Column('training_program_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ENROLLED', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', 'WITHDRAWN', name='enrollmentstatus'), nullable=False),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'training_program_id', name='uq_learner_training_program')
    )
    op.create_index(op.f('ix_training_enrollments_learner_id'), 'training_enrollments', ['learner_id'], unique=False)
    op.create_index(op.f('ix_training_enrollments_training_program_id'), 'training_enrollments', ['training_program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_enrollments_training_program_id'), table_name='training_enrollments')
    op.drop_index(op.f('ix_training_enrollments_learner_id'), table_name='training_enrollments')
    op.drop_table('training_enrollments')
    op.drop_index(op.f('ix_training_programs_provider_id'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_learner_skills_skill_id'), table_name='learner_skills')
    op.drop_index(op.f('ix_learner_skills_learner_id'), table_name='learner_skills')
    op.drop_table('learner_skills')
    op.drop_index(op.f('ix_career_events_learner_id'), table_name='career_events')
    op.drop_table('career_events')
    op.drop_index(op.f('ix_training_providers_user_id'), table_name='training_providers')
    op.drop_table('training_providers')
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_government_admins_user_id'), table_name='government_admins')
    op.drop_table('government_admins')
    op.drop_index(op.f('ix_employers_user_id'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_apaar_identities_user_id'), table_name='apaar_identities')
    op.drop_index(op.f('ix_apaar_identities_apaar_hash'), table_name='apaar_identities')
    op.drop_table('apaar_identities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
